flb: modify section() macro to handle .text section in OSX properly
The released version of libco v18 it's not handling OSX properly when
accessing the text section:

  amd64.c:25:3: error: argument to 'section' attribute is not valid
  for this target: mach-o section specifier requires a segment and
  section separated by a comma

I found this issue was solved by 'mednafen' project using a different
way to access the section:

  __attribute__((section("__TEXT,__text")))

This patch modify settings.h adding some conditionals and using a new
macro to access the text section from the architecture handlers:

 text_section

That's the only section used by libco so it should be fine for now.

Signed-off-by: Eduardo Silva <eduardo@monkey.io>